[package]
org = "ballerinax"
name = "persist.inmemory"
version = "1.1.0"
authors = ["Ballerina"]
keywords = ["persist", "inmemory"]
repository = "https://github.com/ballerina-platform/module-ballerinax-persist.inmemory"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.persist"
artifactId = "persist-inmemory-native"
version = "1.1.0"
path = "../native/build/libs/persist.inmemory-native-1.1.0-SNAPSHOT.jar"
